# Generated by Django 5.1.6 on 2025-03-09 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')]),
        ),
    ]
