# Generated by Django 5.1.6 on 2025-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_specification_productspecification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
