# Generated by Django 5.1.6 on 2025-03-09 20:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/de0pvltpa/image/upload/v1234567/default_product.png', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
