# Generated by Django 5.1.6 on 2025-02-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_specification_color_alter_specification_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='features',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
