# Generated by Django 5.1.6 on 2025-05-18 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆ (Poor)'), (2, '★★☆☆☆ (Fair)'), (3, '★★★☆☆ (Good)'), (4, '★★★★☆ (Very Good)'), (5, '★★★★★ (Excellent)')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
