# Generated by Django 5.1.6 on 2025-03-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_image_alter_productspecification_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='key',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
