# Generated by Django 5.1.6 on 2025-03-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='attached_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
