# Generated by Django 5.1.6 on 2025-02-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productspecification_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='key_features',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='features',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
