# Generated by Django 5.1.6 on 2025-03-07 17:09

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_is_featured_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/de0pvltpa/image/upload/v1234567/default_product.png', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='attached_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='about',
            field=models.TextField(blank=True, default='https://res.cloudinary.com/de0pvltpa/image/upload/v1234567/default_product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='full_name',
            field=models.CharField(blank=True, default="'https://res.cloudinary.com/de0pvltpa/image/upload/v1234567/default_product.png'", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.png', max_length=255, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'WebP', 'jfif'])], verbose_name='image'),
        ),
    ]
