# Generated by Django 5.1.6 on 2025-03-07 17:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_image_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/de0pvltpa/image/upload/v1234567/default_product.png', max_length=255, verbose_name='image'),
        ),
    ]
