# Generated by Django 5.1.6 on 2025-03-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='talks_about',
            field=models.CharField(blank=True, default='anything', max_length=255, null=True),
        ),
    ]
